<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="priya-0711k" failures="2" tests="3" name="Test" time="18.267" errors="0" timestamp="2023-02-14T15:27:02 IST">
  <testcase classname="Testcases.SignUp$Signup" name="signup" time="7.022"/>
  <testcase classname="Testcases.verifyLogin" name="login" time="0.03">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://login.salesforc.com/] but found [https://login.salesforce.com/?locale=in]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://login.salesforc.com/] but found [https://login.salesforce.com/?locale=in]
at Resource.CommonMethods.handleAssertions(CommonMethods.java:26)
at Testcases.verifyLogin.login(verifyLogin.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="Testcases.verifyLogin" name="login" time="0.016">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://login.salesforc.com/] but found [https://login.salesforce.com/?locale=in]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://login.salesforc.com/] but found [https://login.salesforce.com/?locale=in]
at Resource.CommonMethods.handleAssertions(CommonMethods.java:26)
at Testcases.verifyLogin.login(verifyLogin.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
